/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasVeterinario;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import telas.TelasDiretor.EscolheRecinto;
import zoologico.Animal;
import zoologico.GerenciadorArquivos;
import zoologico.Recinto;
import zoologico.Veterinario;

/**
 *
 * @author Vinicius
 */
public class AdicionarAnimal extends javax.swing.JFrame {
    GerenciadorArquivos arquivo;
    Veterinario veterinarioCriador;
    
    // atributos para edição de um animal escolhido
    boolean editor = false;
    Animal animalEscolhido = null;
    
    public AdicionarAnimal() {
        initComponents();        
        
        setLocationRelativeTo(null);
    }
    
    // construtor para a criação de um animal
    public AdicionarAnimal(GerenciadorArquivos arquivo, Veterinario veterinarioCriador) {
        this.arquivo = arquivo;
        initComponents();
        setLocationRelativeTo(null);
        this.veterinarioCriador = veterinarioCriador;
    }
    
    // construtor para a edição de um animal escolhido
    public AdicionarAnimal(GerenciadorArquivos arquivo, int indexLista) {
        this.arquivo = arquivo;
        initComponents();
        setLocationRelativeTo(null);
        
        animalEscolhido = arquivo.getAnimais().get(indexLista);
        editor = true;
        
        txtNome.setText(animalEscolhido.getNome());
        txtCuidadosEspeciais.setText(animalEscolhido.getCuidadosEspeciais());
        txtEspecie.setText(animalEscolhido.getEspecie());
        txtHistorico.setText(animalEscolhido.getHistorico());
        txtSexo.setText(animalEscolhido.getSexo());
        txtTipoSanguineo.setText(animalEscolhido.getTipoSanguineo());
        txtDataNascimento.setText(animalEscolhido.getDataNascimento());
        btnVenenoso.setSelected(animalEscolhido.isVenenoso());
        
        txtNome.setForeground(new Color(0, 0, 0));
        txtCuidadosEspeciais.setForeground(new Color(0, 0, 0));
        txtEspecie.setForeground(new Color(0, 0, 0));
        txtHistorico.setForeground(new Color(0, 0, 0));
        txtSexo.setForeground(new Color(0, 0, 0));
        txtTipoSanguineo.setForeground(new Color(0, 0, 0));
        txtDataNascimento.setForeground(new Color(0, 0, 0));
        
    }

    /**
     * Creates new form AdicionarAnimal
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        txtEspecie = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtTipoSanguineo = new javax.swing.JTextField();
        btnVenenoso = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCuidadosEspeciais = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnConfAnimal = new javax.swing.JButton();
        btnCancAnimal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAlterarRecinto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtEspecie.setForeground(new java.awt.Color(153, 153, 153));
        txtEspecie.setText("Espécie");
        txtEspecie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEspecieFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEspecieFocusLost(evt);
            }
        });
        txtEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieActionPerformed(evt);
            }
        });

        txtNome.setForeground(new java.awt.Color(153, 153, 153));
        txtNome.setText("Nome");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });

        txtDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        txtDataNascimento.setText("Data de nascimento");
        txtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusLost(evt);
            }
        });

        txtSexo.setForeground(new java.awt.Color(153, 153, 153));
        txtSexo.setText("Sexo");
        txtSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSexoFocusLost(evt);
            }
        });

        txtTipoSanguineo.setForeground(new java.awt.Color(153, 153, 153));
        txtTipoSanguineo.setText("Tipo Sanguíneo");
        txtTipoSanguineo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoSanguineoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoSanguineoFocusLost(evt);
            }
        });

        btnVenenoso.setText("É venenoso");
        btnVenenoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenenosoActionPerformed(evt);
            }
        });

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane1.setViewportView(txtHistorico);

        jLabel1.setText("Histórico:");

        txtCuidadosEspeciais.setColumns(20);
        txtCuidadosEspeciais.setRows(5);
        jScrollPane2.setViewportView(txtCuidadosEspeciais);

        jLabel2.setText("Cuidados especiais:");

        btnConfAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904674_accept_approved_check_checked_confirm_icon.png"))); // NOI18N
        btnConfAnimal.setText("CONFIRMAR");
        btnConfAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfAnimalActionPerformed(evt);
            }
        });

        btnCancAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904654_cancel_close_cross_delete_reject_icon.png"))); // NOI18N
        btnCancAnimal.setText("CANCELAR");
        btnCancAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancAnimalActionPerformed(evt);
            }
        });

        jLabel3.setText("ID do recinto:");

        btnAlterarRecinto.setText("Alterar recinto");
        btnAlterarRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarRecintoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVenenoso, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addComponent(txtNome)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnConfAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancAnimal)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btnAlterarRecinto))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVenenoso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(btnAlterarRecinto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfAnimal)
                    .addComponent(btnCancAnimal))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieActionPerformed

    private void txtEspecieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEspecieFocusGained
        if(txtEspecie.getText().equals("Espécie")) {
            txtEspecie.setText("");
            txtEspecie.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtEspecieFocusGained

    private void txtEspecieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEspecieFocusLost
        if(txtEspecie.getText().equals("")) {
            txtEspecie.setText("Espécie");
            txtEspecie.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtEspecieFocusLost

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if(txtNome.getText().equals("Nome")) {
            txtNome.setText("");
            txtNome.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if(txtNome.getText().equals("")) {
            txtNome.setText("Nome");
            txtNome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusGained
        if(txtDataNascimento.getText().equals("Data de nascimento")) {
            txtDataNascimento.setText("");
            txtDataNascimento.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusGained

    private void txtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusLost
        if(txtDataNascimento.getText().equals("")) {
            txtDataNascimento.setText("Data de nascimento");
            txtDataNascimento.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusLost

    private void txtTipoSanguineoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoSanguineoFocusGained
        if(txtTipoSanguineo.getText().equals("Tipo Sanguíneo")) {
            txtTipoSanguineo.setText("");
            txtTipoSanguineo.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtTipoSanguineoFocusGained

    private void txtTipoSanguineoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoSanguineoFocusLost
        if(txtTipoSanguineo.getText().equals("")) {
            txtTipoSanguineo.setText("Tipo Sanguíneo");
            txtTipoSanguineo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtTipoSanguineoFocusLost

    private void txtSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusLost
        if(txtSexo.getText().equals("")) {
            txtSexo.setText("Sexo");
            txtSexo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSexoFocusLost

    private void txtSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusGained
        if(txtSexo.getText().equals("Sexo")) {
            txtSexo.setText("");
            txtSexo.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSexoFocusGained

    private void btnAlterarRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarRecintoActionPerformed
        new EscolheRecinto().setVisible(true);
    }//GEN-LAST:event_btnAlterarRecintoActionPerformed

    private void btnCancAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancAnimalActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancAnimalActionPerformed

    private void btnConfAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfAnimalActionPerformed
        if (txtEspecie.getText().equals("Espécie") || txtNome.getText().equals("Nome") || txtDataNascimento.getText().equals("Data de nascimento") || 
                txtTipoSanguineo.getText().equals("Senha") || txtSexo.getText().equals("Sexo") || 
                txtCuidadosEspeciais.getText().equals("") || txtHistorico.getText().equals("")) 
            {
                
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Campos não preenchidos", JOptionPane.PLAIN_MESSAGE);
        } else {
            
            
            // se estiver editando um animal já criado
            if (editor) {
                animalEscolhido.setNome(txtNome.getText());
                animalEscolhido.setEspecie(txtEspecie.getText());
                animalEscolhido.setDataNascimento(txtDataNascimento.getText());
                animalEscolhido.setTipoSanguineo(txtTipoSanguineo.getText());
                animalEscolhido.setSexo(txtSexo.getText());
                animalEscolhido.setHistorico(txtHistorico.getText());
                animalEscolhido.setCuidadosEspeciais(txtCuidadosEspeciais.getText());
                animalEscolhido.setRecinto(null);
                animalEscolhido.setVenenoso(btnVenenoso.isSelected());
            
            // se estiver criando um animal
            } else {
                Recinto recinto = null;
                ArrayList<String> veterinarios = new ArrayList<String>();
                veterinarios.add(veterinarioCriador.getCpf());
                Animal animalCriado = new Animal(txtEspecie.getText(), txtNome.getText(),txtSexo.getText(),txtDataNascimento.getText(),
                    txtHistorico.getText(),txtCuidadosEspeciais.getText(),
                    btnVenenoso.isSelected(),txtTipoSanguineo.getText(),recinto, veterinarios);
                arquivo.adicionarObjeto(0, animalCriado);
                veterinarioCriador.criarAnimal(animalCriado.getAnimalId());
            }
            
            dispose();                  
        }
    }//GEN-LAST:event_btnConfAnimalActionPerformed

    private void btnVenenosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenenosoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenenosoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarRecinto;
    private javax.swing.JButton btnCancAnimal;
    private javax.swing.JButton btnConfAnimal;
    private javax.swing.JRadioButton btnVenenoso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtCuidadosEspeciais;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTipoSanguineo;
    // End of variables declaration//GEN-END:variables
}
