/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasVeterinario;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import zoologico.GerenciadorArquivos;
import zoologico.Veterinario;

/**
 *
 * @author Vinicius
 */
public class AnalisarAnimal extends javax.swing.JFrame {

    /**
     * Creates new form EditarAnimal
     */
    GerenciadorArquivos arquivo;
    Veterinario veterinarioEscolhido;
    
    public AnalisarAnimal() {
        initComponents();
        carregarTabelaAnimais();
        
        setLocationRelativeTo(null);   
    }
    
    public AnalisarAnimal(GerenciadorArquivos arquivo) {
        this.arquivo = arquivo;
        
        initComponents();
        carregarTabelaAnimais();
        
        setLocationRelativeTo(null);
    }
    
    public AnalisarAnimal(GerenciadorArquivos arquivo, Veterinario veterinarioEscolhido) {
        this.arquivo = arquivo;
        this.veterinarioEscolhido = veterinarioEscolhido;
        
        initComponents();
        carregarTabelaAnimais();
        
        setLocationRelativeTo(null);
    }
    
    public void carregarTabelaAnimais(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Espécie", "Sexo", "Tipo sanguíneo", "Data de nascimento"}, 0);
        ArrayList <String> idAnimais = veterinarioEscolhido.getIdAnimaisResponsavel();
        for(int i=0;i < GerenciadorArquivos.getAnimais().size(); i++) {
            if (idAnimais.contains(GerenciadorArquivos.getAnimais().get(i).getAnimalId())) {
                Object linha[] = new Object[]{GerenciadorArquivos.getAnimais().get(i).getEspecie(),
                                        GerenciadorArquivos.getAnimais().get(i).getSexo(),
                                        GerenciadorArquivos.getAnimais().get(i).getTipoSanguineo(),
                                        GerenciadorArquivos.getAnimais().get(i).getDataNascimento()};
                modelo.addRow(linha);
            }
        }
        tblAnimais.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimais = new javax.swing.JTable();
        txtPesquisarAnimal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisarAnimal = new javax.swing.JButton();
        btnEditarAnimal = new javax.swing.JButton();
        btnDeletarAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Espécie", "Sexo", "Tipo Sanguíneo", "Data de nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAnimais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblAnimaisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblAnimaisFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnimais);
        if (tblAnimais.getColumnModel().getColumnCount() > 0) {
            tblAnimais.getColumnModel().getColumn(0).setPreferredWidth(208);
            tblAnimais.getColumnModel().getColumn(0).setMaxWidth(208);
            tblAnimais.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblAnimais.getColumnModel().getColumn(1).setMaxWidth(100);
            tblAnimais.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblAnimais.getColumnModel().getColumn(2).setMaxWidth(80);
            tblAnimais.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblAnimais.getColumnModel().getColumn(3).setMaxWidth(120);
        }

        jLabel1.setText("Filtrar por espécie:");

        btnPesquisarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3844432-magnifier-search-zoom_110300.png"))); // NOI18N

        btnEditarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_icon-icons.com_61193.png"))); // NOI18N
        btnEditarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAnimalActionPerformed(evt);
            }
        });

        btnDeletarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3844424_can_delete_remove_trash_icon.png"))); // NOI18N
        btnDeletarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisarAnimal)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarAnimal)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnEditarAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeletarAnimal)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPesquisarAnimal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditarAnimal)
                    .addComponent(btnDeletarAnimal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAnimaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblAnimaisFocusGained
        
    }//GEN-LAST:event_tblAnimaisFocusGained

    private void tblAnimaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblAnimaisFocusLost
        
    }//GEN-LAST:event_tblAnimaisFocusLost

    private void btnEditarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAnimalActionPerformed
        if (tblAnimais.getSelectedRowCount() != 0) {
            int index = tblAnimais.getSelectedRow();
            new AdicionarAnimal(arquivo, index).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um recinto da tabela", "Recinto não escolhido", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarAnimalActionPerformed

    private void btnDeletarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarAnimalActionPerformed
        if (tblAnimais.getSelectedRowCount() != 0) {
            int index = tblAnimais.getSelectedRow();
        
            if (index>=0 && index<GerenciadorArquivos.getAnimais().size()) {
                arquivo.removerObjeto(0, GerenciadorArquivos.getAnimais().get(index));
                carregarTabelaAnimais();
                
                
            }
        } else if (tblAnimais.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Escolha apenas um animal da tabela", "Mais de um animal escolhido", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Escolha um animal da tabela", "Animal não escolhido", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnDeletarAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalisarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalisarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalisarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalisarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalisarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarAnimal;
    private javax.swing.JButton btnEditarAnimal;
    private javax.swing.JButton btnPesquisarAnimal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnimais;
    private javax.swing.JTextField txtPesquisarAnimal;
    // End of variables declaration//GEN-END:variables
}
