/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasVeterinario;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import telas.EditarPerfil;
import zoologico.GerenciadorArquivos;
import zoologico.Veterinario;
import zoologico.Funcionario;

/**
 *
 * @author Vinicius
 */
public class VeterinarioTela extends javax.swing.JFrame {

    /**
     * Creates new form Veterinario
     * @param arquivo
     */
    GerenciadorArquivos arquivo;
    Veterinario veterinarioEscolhido;
    
    public VeterinarioTela(GerenciadorArquivos arquivo, Veterinario veterinarioEscolhido) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.arquivo = arquivo;
        this.veterinarioEscolhido = veterinarioEscolhido;
        
        txtNome.setText(veterinarioEscolhido.getNome());
        
        
        addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    try {
                        arquivo.exportarArquivos();
                    } catch (Exception ex) {}
                }
            });
    }
    
    public VeterinarioTela() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();
        btnAdicionarAnimal = new javax.swing.JButton();
        btnAnalisarAnimal = new javax.swing.JButton();
        txtNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setText("Bem-vindo ");

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel2.setText("Cargo: Veterinário");

        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lapis.png"))); // NOI18N
        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarPerfil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        btnAdicionarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3204625_add_animal_cat_domestic_pet_icon (1).png"))); // NOI18N
        btnAdicionarAnimal.setText("ADICIONAR ANIMAL");
        btnAdicionarAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarAnimal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAdicionarAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAnimalActionPerformed(evt);
            }
        });

        btnAnalisarAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2931174_clipboard_copy_paste_analysis_report_icon.png"))); // NOI18N
        btnAnalisarAnimal.setText("ANALISAR ANIMAIS");
        btnAnalisarAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnalisarAnimal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAnalisarAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnalisarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarAnimalActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        txtNome.setText("(nome)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(btnEditarPerfil)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAdicionarAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnAnalisarAnimal)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEditarPerfil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnalisarAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdicionarAnimal))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAnimalActionPerformed
        new AdicionarAnimal(arquivo).setVisible(true);
    }//GEN-LAST:event_btnAdicionarAnimalActionPerformed

    private void btnAnalisarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarAnimalActionPerformed
        new AnalisarAnimal(arquivo).setVisible(true);
    }//GEN-LAST:event_btnAnalisarAnimalActionPerformed

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        new EditarPerfil(arquivo, (Funcionario) veterinarioEscolhido).setVisible(true);
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeterinarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeterinarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeterinarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeterinarioTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeterinarioTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAnimal;
    private javax.swing.JButton btnAnalisarAnimal;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
