/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasBiologo;

import zoologico.GerenciadorArquivos;

/**
 *
 * @author Vinicius
 */
public class AdicionarRecinto extends javax.swing.JFrame {
    GerenciadorArquivos arquivo;
    /**
     * Creates new form AdicionarRecinto
     */
    public AdicionarRecinto(GerenciadorArquivos arquivo) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.arquivo = arquivo;
    }
    
    public AdicionarRecinto() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMamifero = new javax.swing.JButton();
        btnReptil = new javax.swing.JButton();
        btnAve = new javax.swing.JButton();
        btnAnfibio = new javax.swing.JButton();
        btnPeixe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnMamifero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mamifero.png"))); // NOI18N
        btnMamifero.setText("MAMÍFERO");
        btnMamifero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMamifero.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMamifero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMamifero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMamiferoActionPerformed(evt);
            }
        });

        btnReptil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reptil.png"))); // NOI18N
        btnReptil.setText("RÉPTIL");
        btnReptil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReptil.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnReptil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReptil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReptilActionPerformed(evt);
            }
        });

        btnAve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/birdave.png"))); // NOI18N
        btnAve.setText("AVE");
        btnAve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAve.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAve.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAveActionPerformed(evt);
            }
        });

        btnAnfibio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anfibio.png"))); // NOI18N
        btnAnfibio.setText("ANFÍBIO");
        btnAnfibio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnfibio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAnfibio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnfibio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnfibioActionPerformed(evt);
            }
        });

        btnPeixe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peixe.png"))); // NOI18N
        btnPeixe.setText("PEIXE");
        btnPeixe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeixe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPeixe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeixeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Selecione um tipo de recinto para construir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAve, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReptil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMamifero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnPeixe, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnAnfibio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReptil)
                    .addComponent(btnMamifero)
                    .addComponent(btnAve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnfibio)
                    .addComponent(btnPeixe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMamiferoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMamiferoActionPerformed
        new RecintoMamiferoTela(arquivo).setVisible(true);
    }//GEN-LAST:event_btnMamiferoActionPerformed

    private void btnAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAveActionPerformed
        new RecintoAveTela(arquivo).setVisible(true);
    }//GEN-LAST:event_btnAveActionPerformed

    private void btnReptilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReptilActionPerformed
        new RecintoRepteisTela(arquivo).setVisible(true);
    }//GEN-LAST:event_btnReptilActionPerformed

    private void btnPeixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeixeActionPerformed
        new RecintoPeixeTela(arquivo).setVisible(true);
    }//GEN-LAST:event_btnPeixeActionPerformed

    private void btnAnfibioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnfibioActionPerformed
        new RecintoAnfibioTela(arquivo).setVisible(true);
    }//GEN-LAST:event_btnAnfibioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarRecinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnfibio;
    private javax.swing.JButton btnAve;
    private javax.swing.JButton btnMamifero;
    private javax.swing.JButton btnPeixe;
    private javax.swing.JButton btnReptil;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
