/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasBiologo;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import telas.EditarPerfil;
import zoologico.Biologo;
import zoologico.GerenciadorArquivos;

// Tela de início do biólogo

/**
 *
 * @author Vinicius
 */
public class BiologoTela extends javax.swing.JFrame {
    GerenciadorArquivos arquivo;
    Biologo biologoEscolhido;
    /**
     * Creates new form Biologo
     * @param arquivo
     */
    public BiologoTela() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    public BiologoTela(GerenciadorArquivos arquivo, Biologo biologoEscolhido) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.arquivo = arquivo;
        this.biologoEscolhido = biologoEscolhido;
        
        txtNome.setText(biologoEscolhido.getNome());
        
        addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    try {
                        arquivo.exportarArquivos();
                    } catch (Exception ex) {}
                }
            });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();
        btnAdicionarRecinto = new javax.swing.JButton();
        btnAnalisarRecinto = new javax.swing.JButton();
        txtNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setText("Bem-vindo");
        jLabel1.setMaximumSize(new java.awt.Dimension(162, 1));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel2.setText("Cargo: Biólogo");

        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lapis.png"))); // NOI18N
        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarPerfil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        btnAdicionarRecinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tree_icon_184603 (1).png"))); // NOI18N
        btnAdicionarRecinto.setText("ADICIONAR RECINTO");
        btnAdicionarRecinto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarRecinto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAdicionarRecinto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarRecintoActionPerformed(evt);
            }
        });

        btnAnalisarRecinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2931174_clipboard_copy_paste_analysis_report_icon.png"))); // NOI18N
        btnAnalisarRecinto.setText("ANALISAR RECINTOS");
        btnAnalisarRecinto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnalisarRecinto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAnalisarRecinto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnalisarRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarRecintoActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        txtNome.setText("(nome)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btnEditarPerfil)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnAdicionarRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnalisarRecinto)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarPerfil)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionarRecinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnalisarRecinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        new EditarPerfil(arquivo, biologoEscolhido).setVisible(true);
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    private void btnAdicionarRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarRecintoActionPerformed
        new AdicionarRecinto(arquivo, biologoEscolhido).setVisible(true);
    }//GEN-LAST:event_btnAdicionarRecintoActionPerformed

    private void btnAnalisarRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarRecintoActionPerformed
        new AnalisarRecinto(arquivo, biologoEscolhido).setVisible(true);
    }//GEN-LAST:event_btnAnalisarRecintoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiologoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiologoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiologoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiologoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiologoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarRecinto;
    private javax.swing.JButton btnAnalisarRecinto;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
