/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasBiologo;

import java.awt.Color;
import javax.swing.UIManager;
import zoologico.Animal;

// Tela para exibir o perfil de um animal específico que foi selecionado na edição ou criação de um recinto

/**
 *
 * @author Vinicius
 */
public class PerfilAnimal extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarAnimal
     */
    public PerfilAnimal() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    public PerfilAnimal(Animal animalEscolhido) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        txtNome.setText(animalEscolhido.getNome());
        txtCuidadosEspeciais.setText(animalEscolhido.getCuidadosEspeciais());
        txtEspecie.setText(animalEscolhido.getEspecie());
        txtHistorico.setText(animalEscolhido.getHistorico());
        txtSexo.setText(animalEscolhido.getSexo());
        txtTipoSanguineo.setText(animalEscolhido.getTipoSanguineo());
        txtDataNascimento.setText(animalEscolhido.getDataNascimento());
        btnVenenoso.setSelected(animalEscolhido.isVenenoso());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEspecie = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtTipoSanguineo = new javax.swing.JTextField();
        btnVenenoso = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCuidadosEspeciais = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtEspecie.setForeground(new java.awt.Color(153, 153, 153));
        txtEspecie.setText("Espécie");
        txtEspecie.setEnabled(false);
        txtEspecie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEspecieFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEspecieFocusLost(evt);
            }
        });
        txtEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieActionPerformed(evt);
            }
        });

        txtNome.setForeground(new java.awt.Color(153, 153, 153));
        txtNome.setText("Nome");
        txtNome.setEnabled(false);
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });

        txtDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        txtDataNascimento.setText("Data de nascimento");
        txtDataNascimento.setEnabled(false);
        txtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusLost(evt);
            }
        });

        txtSexo.setForeground(new java.awt.Color(153, 153, 153));
        txtSexo.setText("Sexo");
        txtSexo.setEnabled(false);
        txtSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSexoFocusLost(evt);
            }
        });

        txtTipoSanguineo.setForeground(new java.awt.Color(153, 153, 153));
        txtTipoSanguineo.setText("Tipo Sanguíneo");
        txtTipoSanguineo.setEnabled(false);
        txtTipoSanguineo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoSanguineoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoSanguineoFocusLost(evt);
            }
        });

        btnVenenoso.setText("É venenoso");
        btnVenenoso.setEnabled(false);

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        txtHistorico.setEnabled(false);
        jScrollPane1.setViewportView(txtHistorico);

        jLabel1.setText("Histórico:");

        txtCuidadosEspeciais.setColumns(20);
        txtCuidadosEspeciais.setRows(5);
        txtCuidadosEspeciais.setEnabled(false);
        jScrollPane2.setViewportView(txtCuidadosEspeciais);

        jLabel2.setText("Cuidados especiais:");

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel3.setText("Perfil do animal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVenenoso, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addComponent(txtNome)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVenenoso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieActionPerformed

    private void txtEspecieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEspecieFocusGained
        if(txtEspecie.getText().equals("Espécie")) {
            txtEspecie.setText("");
            txtEspecie.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtEspecieFocusGained

    private void txtEspecieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEspecieFocusLost
        if(txtEspecie.getText().equals("")) {
            txtEspecie.setText("Espécie");
            txtEspecie.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtEspecieFocusLost

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if(txtNome.getText().equals("Nome")) {
            txtNome.setText("");
            txtNome.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if(txtNome.getText().equals("")) {
            txtNome.setText("Nome");
            txtNome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusGained
        if(txtDataNascimento.getText().equals("Data de nascimento")) {
            txtDataNascimento.setText("");
            txtDataNascimento.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusGained

    private void txtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusLost
        if(txtDataNascimento.getText().equals("")) {
            txtDataNascimento.setText("Data de nascimento");
            txtDataNascimento.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusLost

    private void txtTipoSanguineoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoSanguineoFocusGained
        if(txtTipoSanguineo.getText().equals("Tipo Sanguíneo")) {
            txtTipoSanguineo.setText("");
            txtTipoSanguineo.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtTipoSanguineoFocusGained

    private void txtTipoSanguineoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoSanguineoFocusLost
        if(txtTipoSanguineo.getText().equals("")) {
            txtTipoSanguineo.setText("Tipo Sanguíneo");
            txtTipoSanguineo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtTipoSanguineoFocusLost

    private void txtSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusLost
        if(txtSexo.getText().equals("")) {
            txtSexo.setText("Sexo");
            txtSexo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSexoFocusLost

    private void txtSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusGained
        if(txtSexo.getText().equals("Sexo")) {
            txtSexo.setText("");
            txtSexo.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSexoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnVenenoso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCuidadosEspeciais;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTipoSanguineo;
    // End of variables declaration//GEN-END:variables
}
