/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasBiologo;

import telas.TelasVeterinario.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import zoologico.Animal;
import zoologico.GerenciadorArquivos;
import zoologico.RecintoMamifero;

/**
 *
 * @author Vinicius
 */
public class RecintoMamiferoTela extends javax.swing.JFrame {
    GerenciadorArquivos arquivo;
    /**
     * Creates new form AdicionarAnimal
     * @param arquivo
     */
    public RecintoMamiferoTela(GerenciadorArquivos arquivo) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.arquivo = arquivo;
    }
    
    public RecintoMamiferoTela() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        txtVegetacao = new javax.swing.JTextField();
        btnConfAnimal = new javax.swing.JButton();
        btnCancAnimal = new javax.swing.JButton();
        jrDiurno = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAnimais = new javax.swing.JTable();
        btnOlharAnimal = new javax.swing.JButton();
        txtFamilia = new javax.swing.JTextField();
        jrPoleiro = new javax.swing.JRadioButton();
        jrAquatico = new javax.swing.JRadioButton();
        jrArboricola = new javax.swing.JRadioButton();
        txtArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtVegetacao.setForeground(new java.awt.Color(153, 153, 153));
        txtVegetacao.setText("Tipo de vegetação");
        txtVegetacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVegetacaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVegetacaoFocusLost(evt);
            }
        });
        txtVegetacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVegetacaoActionPerformed(evt);
            }
        });

        btnConfAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904674_accept_approved_check_checked_confirm_icon.png"))); // NOI18N
        btnConfAnimal.setText("CONFIRMAR");
        btnConfAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfAnimalActionPerformed(evt);
            }
        });

        btnCancAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904654_cancel_close_cross_delete_reject_icon.png"))); // NOI18N
        btnCancAnimal.setText("CANCELAR");
        btnCancAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancAnimalActionPerformed(evt);
            }
        });

        jrDiurno.setText("Diurno");

        jLabel1.setText("Animais do recinto:");

        tblAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Espécie", "Sexo", "Data de Nascimento"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    tblAnimais.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            tblAnimaisFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            tblAnimaisFocusLost(evt);
        }
    });
    jScrollPane2.setViewportView(tblAnimais);

    btnOlharAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho.png"))); // NOI18N
    btnOlharAnimal.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            btnOlharAnimalFocusGained(evt);
        }
    });
    btnOlharAnimal.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOlharAnimalActionPerformed(evt);
        }
    });

    txtFamilia.setForeground(new java.awt.Color(153, 153, 153));
    txtFamilia.setText("Família do recinto");
    txtFamilia.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txtFamiliaFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtFamiliaFocusLost(evt);
        }
    });

    jrPoleiro.setText("Possui poleiro");

    jrAquatico.setText("É aquático");

    jrArboricola.setText("Espécies arborícolas");

    txtArea.setForeground(new java.awt.Color(153, 153, 153));
    txtArea.setText("Área total");
    txtArea.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txtAreaFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtAreaFocusLost(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtFamilia)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(txtVegetacao)
                    .addGap(18, 18, 18)
                    .addComponent(jrDiurno))
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(btnConfAnimal)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                    .addComponent(btnCancAnimal)
                    .addGap(41, 41, 41))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOlharAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jrPoleiro)
                            .addGap(18, 18, 18)
                            .addComponent(jrAquatico)
                            .addGap(18, 18, 18)
                            .addComponent(jrArboricola))
                        .addComponent(jLabel1)
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(txtFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtVegetacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jrDiurno))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jrPoleiro)
                .addComponent(jrAquatico)
                .addComponent(jrArboricola))
            .addGap(18, 18, 18)
            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(btnOlharAnimal)
                    .addGap(109, 109, 109)))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnConfAnimal)
                .addComponent(btnCancAnimal))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVegetacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVegetacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVegetacaoActionPerformed

    private void txtVegetacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVegetacaoFocusGained
        if(txtVegetacao.getText().equals("Tipo de vegetação")) {
            txtVegetacao.setText("");
            txtVegetacao.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtVegetacaoFocusGained

    private void txtVegetacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVegetacaoFocusLost
        if(txtVegetacao.getText().equals("")) {
            txtVegetacao.setText("Tipo de vegetação");
            txtVegetacao.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtVegetacaoFocusLost

    private void btnOlharAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlharAnimalActionPerformed
        if (tblAnimais.getSelectedRowCount() == 1) {
            new PerfilAnimal().setVisible(true);
        } else if (tblAnimais.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Escolha apenas um animal da tabela", "Mais de um animal escolhido", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Escolha um animal da tabela", "Animal não escolhido", JOptionPane.PLAIN_MESSAGE);
        };
    }//GEN-LAST:event_btnOlharAnimalActionPerformed

    private void txtFamiliaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFamiliaFocusGained
        if(txtFamilia.getText().equals("Família do recinto")) {
            txtFamilia.setText("");
            txtFamilia.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtFamiliaFocusGained

    private void txtFamiliaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFamiliaFocusLost
        if(txtFamilia.getText().equals("")) {
            txtFamilia.setText("Família do recinto");
            txtFamilia.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtFamiliaFocusLost

    private void txtAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaFocusGained
        if(txtArea.getText().equals("Área total")) {
            txtArea.setText("");
            txtArea.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtAreaFocusGained

    private void txtAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaFocusLost
        if(txtArea.getText().equals("")) {
            txtArea.setText("Área total");
            txtArea.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtAreaFocusLost

    private void tblAnimaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblAnimaisFocusGained
        
    }//GEN-LAST:event_tblAnimaisFocusGained

    private void tblAnimaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblAnimaisFocusLost
        
        
    }//GEN-LAST:event_tblAnimaisFocusLost

    private void btnCancAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancAnimalActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancAnimalActionPerformed

    private void btnOlharAnimalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnOlharAnimalFocusGained
        
    }//GEN-LAST:event_btnOlharAnimalFocusGained

    private void btnConfAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfAnimalActionPerformed
        if (txtFamilia.getText().equals("Família do recinto") || txtVegetacao.getText().equals("Tipo de vegetação") || txtArea.getText().equals("Área total")) 
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Campos não preenchidos", JOptionPane.PLAIN_MESSAGE);
        } else {
            dispose();
            
            ArrayList<Animal> animais = null;
            RecintoMamifero recintoMamCriado = new RecintoMamifero(jrPoleiro.isSelected(), jrAquatico.isSelected(), jrArboricola.isSelected(), 
                                                Double.parseDouble(txtArea.getText()), txtVegetacao.getText(),
                                                jrDiurno.isSelected(), animais, txtFamilia.getText());
            arquivo.adicionarObjeto(2, recintoMamCriado);
        }
    }//GEN-LAST:event_btnConfAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecintoMamiferoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecintoMamiferoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecintoMamiferoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecintoMamiferoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecintoMamiferoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancAnimal;
    private javax.swing.JButton btnConfAnimal;
    private javax.swing.JButton btnOlharAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrAquatico;
    private javax.swing.JRadioButton jrArboricola;
    private javax.swing.JRadioButton jrDiurno;
    private javax.swing.JRadioButton jrPoleiro;
    private javax.swing.JTable tblAnimais;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtFamilia;
    private javax.swing.JTextField txtVegetacao;
    // End of variables declaration//GEN-END:variables
}
