/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author gugas
 */
public class EditarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarFuncionario
     */
    public EditarPerfil() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtCr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnConfirmarPerfil = new javax.swing.JButton();
        btnCancelarPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNome.setForeground(new java.awt.Color(153, 153, 153));
        txtNome.setText("Nome");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });

        txtCpf.setForeground(new java.awt.Color(153, 153, 153));
        txtCpf.setText("CPF");
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });

        txtDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        txtDataNascimento.setText("Data de nascimento");
        txtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusLost(evt);
            }
        });
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });

        txtSexo.setForeground(new java.awt.Color(153, 153, 153));
        txtSexo.setText("Sexo");
        txtSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSexoFocusLost(evt);
            }
        });

        txtSenha.setForeground(new java.awt.Color(153, 153, 153));
        txtSenha.setText("Senha");
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        txtCr.setForeground(new java.awt.Color(153, 153, 153));
        txtCr.setText("CR");
        txtCr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCrFocusLost(evt);
            }
        });

        btnConfirmarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904674_accept_approved_check_checked_confirm_icon.png"))); // NOI18N
        btnConfirmarPerfil.setText("CONFIRMAR");
        btnConfirmarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfirmarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfirmarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPerfilActionPerformed(evt);
            }
        });

        btnCancelarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904654_cancel_close_cross_delete_reject_icon.png"))); // NOI18N
        btnCancelarPerfil.setText("CANCELAR");
        btnCancelarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNome)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(txtSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addComponent(txtSenha))
                    .addComponent(txtCr, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnConfirmarPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarPerfil)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmarPerfil))
                    .addComponent(btnCancelarPerfil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void btnCancelarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPerfilActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarPerfilActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if(txtNome.getText().equals("Nome")) {
            txtNome.setText("");
            txtNome.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if(txtNome.getText().equals("")) {
            txtNome.setText("Nome");
            txtNome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        if(txtCpf.getText().equals("CPF")) {
            txtCpf.setText("");
            txtCpf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtCpfFocusGained

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        if(txtCpf.getText().equals("")) {
            txtCpf.setText("CPF");
            txtCpf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCpfFocusLost

    private void txtDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusGained
        if(txtDataNascimento.getText().equals("Data de nascimento")) {
            txtDataNascimento.setText("");
            txtDataNascimento.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusGained

    private void txtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusLost
        if(txtDataNascimento.getText().equals("")) {
            txtDataNascimento.setText("Data de nascimento");
            txtDataNascimento.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusLost

    private void txtSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusGained
        if(txtSexo.getText().equals("Sexo")) {
            txtSexo.setText("");
            txtSexo.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSexoFocusGained

    private void txtSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusLost
        if(txtSexo.getText().equals("")) {
            txtSexo.setText("Sexo");
            txtSexo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSexoFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        if(txtSenha.getText().equals("Senha")) {
            txtSenha.setText("");
            txtSenha.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        if(txtSenha.getText().equals("")) {
            txtSenha.setText("Senha");
            txtSenha.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void txtCrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrFocusGained
        if(txtCr.getText().equals("CR")) {
            txtCr.setText("");
            txtCr.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtCrFocusGained

    private void txtCrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrFocusLost
        if(txtCr.getText().equals("")) {
            txtCr.setText("CR");
            txtCr.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCrFocusLost

    private void btnConfirmarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPerfilActionPerformed
        if (txtNome.getText().equals("Nome") || txtCpf.getText().equals("CPF") || txtDataNascimento.getText().equals("Data de nascimento") || 
                txtSexo.getText().equals("Sexo") || txtSenha.getText().equals("Senha") || txtCr.getText().equals("CR")) 
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Campos não preenchidos", JOptionPane.PLAIN_MESSAGE);
        } else {
            dispose();
        }
    }//GEN-LAST:event_btnConfirmarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPerfil;
    private javax.swing.JButton btnConfirmarPerfil;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCr;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
