/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasDiretor;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import zoologico.Animal;
import zoologico.Biologo;
import zoologico.Funcionario;
import zoologico.GerenciadorArquivos;
import zoologico.Recinto;
import zoologico.Veterinario;

/**
 *
 * @author gugas
 */
public class AdicionarFuncionario extends javax.swing.JFrame {
    GerenciadorArquivos arquivo;
    /**
     * Creates new form AdicionarFuncionario
     */
    static ArrayList<Animal> listaAnimais;
    boolean flag;
    
    boolean editor = false;
    Funcionario funcionarioEscolhido;
    
    public AdicionarFuncionario(GerenciadorArquivos arquivo, int indexLista) {
        initComponents();
        flag = false;
        btnDelResponsabilidades.setEnabled(false);
        btnAddResponsabilidade.setEnabled(false);
        
        funcionarioEscolhido = arquivo.getFuncionarios().get(indexLista);
        editor = true;

        setLocationRelativeTo(null);

        this.arquivo = arquivo;
        
        txtNome.setText(funcionarioEscolhido.getNome());
        txtCpf.setText(funcionarioEscolhido.getCpf());
        txtCr.setText(funcionarioEscolhido.getCr());
        txtSexo.setText(funcionarioEscolhido.getSexo());
        txtDataNascimento.setText(funcionarioEscolhido.getDataNascimento());
        txtSenha.setText(funcionarioEscolhido.getSenha());
        
        txtNome.setForeground(new Color(0, 0, 0));
        txtCpf.setForeground(new Color(0, 0, 0));
        txtCr.setForeground(new Color(0, 0, 0));
        txtSexo.setForeground(new Color(0, 0, 0));
        txtSenha.setForeground(new Color(0, 0, 0));
        txtDataNascimento.setForeground(new Color(0, 0, 0));
    }
    
    public AdicionarFuncionario(GerenciadorArquivos arquivo) {
        initComponents();
        flag = false;
        btnDelResponsabilidades.setEnabled(false);
        btnAddResponsabilidade.setEnabled(false);
        
        setLocationRelativeTo(null);
        
        this.arquivo = arquivo;
    }
    
    public AdicionarFuncionario() {
        initComponents();
        flag = false;
        btnDelResponsabilidades.setEnabled(false);
        btnAddResponsabilidade.setEnabled(false);
        
        setLocationRelativeTo(null);
    }
    
    public void carregarTabelaAnimais(){
        //DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Espécie", "Nome"}, 0);
        
        //for(int i=0;i < listaAnimais.size(); i++) {
        //    Object linha[] = new Object[]{listaAnimais.get(i).getEspecie(), listaAnimais.get(i).getNome()};
        //    modelo.addRow(linha);
        //}
        tblResponsabilidades.setModel(new DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "Espécie", "Nome"
            }
        ));
        //tblResponsabilidades.setModel(modelo);
        
        
    }
    
    
    public void carregarTabelaRecintos(){
        //DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Espécie", "Nome"}, 0);
        
        //for(int i=0;i < listaAnimais.size(); i++) {
        //    Object linha[] = new Object[]{listaAnimais.get(i).getEspecie(), listaAnimais.get(i).getNome()};
        //    modelo.addRow(linha);
        //}
        
        
        
        DefaultTableModel modelo = new DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "Tipo de recinto", "Família"
            }
        );
        tblResponsabilidades.setModel(modelo);
        //tblResponsabilidades.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        jrbVeterinario = new javax.swing.JRadioButton();
        jrbBiologo = new javax.swing.JRadioButton();
        txtCr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnConfAnimal = new javax.swing.JButton();
        btnCancAnimal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResponsabilidades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAddResponsabilidade = new javax.swing.JButton();
        btnDelResponsabilidades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNome.setForeground(new java.awt.Color(153, 153, 153));
        txtNome.setText("Nome");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtCpf.setForeground(new java.awt.Color(153, 153, 153));
        txtCpf.setText("CPF");
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });

        txtDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        txtDataNascimento.setText("Data de nascimento");
        txtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusLost(evt);
            }
        });
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });

        txtSexo.setForeground(new java.awt.Color(153, 153, 153));
        txtSexo.setText("Sexo");
        txtSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSexoFocusLost(evt);
            }
        });

        txtSenha.setForeground(new java.awt.Color(153, 153, 153));
        txtSenha.setText("Senha");
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        lblCargo.setText("Cargo:");

        buttonGroup1.add(jrbVeterinario);
        jrbVeterinario.setText("Veterinário");
        jrbVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVeterinarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbBiologo);
        jrbBiologo.setText("Biólogo");
        jrbBiologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBiologoActionPerformed(evt);
            }
        });

        txtCr.setForeground(new java.awt.Color(153, 153, 153));
        txtCr.setText("CR");
        txtCr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCrFocusLost(evt);
            }
        });

        btnConfAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904674_accept_approved_check_checked_confirm_icon.png"))); // NOI18N
        btnConfAnimal.setText("CONFIRMAR");
        btnConfAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfAnimalActionPerformed(evt);
            }
        });

        btnCancAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1904654_cancel_close_cross_delete_reject_icon.png"))); // NOI18N
        btnCancAnimal.setText("CANCELAR");
        btnCancAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancAnimalActionPerformed(evt);
            }
        });

        tblResponsabilidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblResponsabilidades);

        jLabel1.setText("Responsabilidades:");

        btnAddResponsabilidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnAddResponsabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddResponsabilidadeActionPerformed(evt);
            }
        });

        btnDelResponsabilidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_32.png"))); // NOI18N
        btnDelResponsabilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelResponsabilidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnConfAnimal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancAnimal)
                                .addGap(55, 55, 55))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAddResponsabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(btnDelResponsabilidades))))
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(txtSexo))
                                .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(jrbVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jrbBiologo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)))
                            .addComponent(jLabel1)
                            .addComponent(txtCr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbVeterinario)
                    .addComponent(jrbBiologo))
                .addGap(18, 18, 18)
                .addComponent(txtCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfAnimal))
                            .addComponent(btnCancAnimal))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAddResponsabilidade)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelResponsabilidades)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void jrbBiologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBiologoActionPerformed
        btnAddResponsabilidade.setEnabled(true);
        carregarTabelaRecintos();
    }//GEN-LAST:event_jrbBiologoActionPerformed

    private void jrbVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVeterinarioActionPerformed
        btnAddResponsabilidade.setEnabled(true);
        carregarTabelaAnimais();
    }//GEN-LAST:event_jrbVeterinarioActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if(txtNome.getText().equals("Nome")) {
            txtNome.setText("");
            txtNome.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if(txtNome.getText().equals("")) {
            txtNome.setText("Nome");
            txtNome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        if(txtCpf.getText().equals("CPF")) {
            txtCpf.setText("");
            txtCpf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtCpfFocusGained

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        if(txtCpf.getText().equals("")) {
            txtCpf.setText("CPF");
            txtCpf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCpfFocusLost

    private void txtDataNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusGained
        if(txtDataNascimento.getText().equals("Data de nascimento")) {
            txtDataNascimento.setText("");
            txtDataNascimento.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusGained

    private void txtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusLost
        if(txtDataNascimento.getText().equals("")) {
            txtDataNascimento.setText("Data de nascimento");
            txtDataNascimento.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtDataNascimentoFocusLost

    private void txtSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusGained
        if(txtSexo.getText().equals("Sexo")) {
            txtSexo.setText("");
            txtSexo.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSexoFocusGained

    private void txtSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSexoFocusLost
        if(txtSexo.getText().equals("")) {
            txtSexo.setText("Sexo");
            txtSexo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSexoFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        if(txtSenha.getText().equals("Senha")) {
            txtSenha.setText("");
            txtSenha.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        if(txtSenha.getText().equals("")) {
            txtSenha.setText("Senha");
            txtSenha.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void txtCrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrFocusGained
        if(txtCr.getText().equals("CR")) {
            txtCr.setText("");
            txtCr.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtCrFocusGained

    private void txtCrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrFocusLost
        if(txtCr.getText().equals("")) {
            txtCr.setText("CR");
            txtCr.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCrFocusLost

    private void btnAddResponsabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddResponsabilidadeActionPerformed
        //boolean penis = jrbVeterinario.isSelected() ? "a" : "b";
        if (jrbVeterinario.isSelected()) {
            new EscolheAnimal().setVisible(true);
        } else {
            new EscolheRecinto().setVisible(true);
        }
        //new EscolheAnimal().setVisible(true);
        //new PerfilRecinto().setVisible(true);
        //jrbVeterinario.isSelected() ? new EscolheAnimal().setVisible(true) : new PerfilRecinto().setVisible(true);
        //flag ? new EscolheAnimal().setVisible(true): new PerfilRecinto().setVisible(true);
    }//GEN-LAST:event_btnAddResponsabilidadeActionPerformed

    private void btnDelResponsabilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelResponsabilidadesActionPerformed
        if (tblResponsabilidades.getSelectedRowCount() == 1) {
            
        } else if (tblResponsabilidades.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Escolha apenas uma responsabilidade da tabela", "Mais de uma responsabilidade escolhido", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Escolha uma responsabilidade da tabela", "Responsabilidade não escolhida", JOptionPane.PLAIN_MESSAGE);
        };
       
    }//GEN-LAST:event_btnDelResponsabilidadesActionPerformed

    private void btnCancAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancAnimalActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancAnimalActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnConfAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfAnimalActionPerformed
        if (txtCpf.getText().equals("CPF") || txtNome.getText().equals("Nome") || txtDataNascimento.getText().equals("Data de nascimento") || 
                txtSenha.getText().equals("Senha") || txtSexo.getText().equals("Sexo") || txtCr.getText().equals("CR")) 
            {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Campos não preenchidos", JOptionPane.PLAIN_MESSAGE);
        } else {
            
            
            // se estiver editando um animal já criado
            if (editor) {
                funcionarioEscolhido.setNome(txtNome.getText());
                funcionarioEscolhido.setCpf(txtCpf.getText());
                funcionarioEscolhido.setDataNascimento(txtDataNascimento.getText());
                funcionarioEscolhido.setSenha(txtSenha.getText());
                funcionarioEscolhido.setSexo(txtSexo.getText());
                funcionarioEscolhido.setCr(txtCr.getText());
            
            // se estiver criando um animal
            } else {
                //Recinto recinto = null;
                if (jrbBiologo.isSelected()) {
                    ArrayList<Recinto> recintos = null;
                    Biologo biologoCriado = new Biologo(txtCr.getText(), recintos, txtNome.getText(), txtCpf.getText(), txtDataNascimento.getText(), txtSexo.getText(), txtSenha.getText());
                    
                    arquivo.adicionarObjeto(1, biologoCriado);
                } else {
                    ArrayList<Animal> animais = null;
                    Veterinario vetCriado = new Veterinario(txtCr.getText(), animais, txtNome.getText(), txtCpf.getText(), txtDataNascimento.getText(), txtSexo.getText(), txtSenha.getText());
                    
                    arquivo.adicionarObjeto(1, vetCriado);
                }
                
            //}
            
            try {
                //arquivo.exportarArquivos();
            } catch (Exception ex) {
                
            }
            dispose();
        }
    }//GEN-LAST:event_btnConfAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddResponsabilidade;
    private javax.swing.JButton btnCancAnimal;
    private javax.swing.JButton btnConfAnimal;
    private javax.swing.JButton btnDelResponsabilidades;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrbBiologo;
    private javax.swing.JRadioButton jrbVeterinario;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JTable tblResponsabilidades;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCr;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
