/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasDiretor;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import zoologico.Biologo;
import zoologico.GerenciadorArquivos;

/**
 *
 * @author gugas
 */
public class AnalisarFuncionario extends javax.swing.JFrame {
    GerenciadorArquivos arquivo;
    /**
     * Creates new form AnalisarFuncionario
     */
    public AnalisarFuncionario(GerenciadorArquivos arquivo) {
        initComponents();
        
        setLocationRelativeTo(null);
        carregarTabelaFuncionarios();
       
    }
    
    public AnalisarFuncionario() {
        initComponents();
        
        setLocationRelativeTo(null);
        carregarTabelaFuncionarios();
       
    }
    
    public void carregarTabelaFuncionarios(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"CPF", "Nome", "Data de nascimento", "Sexo", "Cargo", "CR"}, 0);
        
        for(int i=0;i < GerenciadorArquivos.getFuncionarios().size(); i++) {
            
            Object linha[] = new Object[]{GerenciadorArquivos.getFuncionarios().get(i).getCpf(),
                                        GerenciadorArquivos.getFuncionarios().get(i).getNome(),
                                        GerenciadorArquivos.getFuncionarios().get(i).getDataNascimento(),
                                        GerenciadorArquivos.getFuncionarios().get(i).getSexo(),
                                        GerenciadorArquivos.getFuncionarios().get(i) instanceof Biologo ? "Biólogo" : "Veterinário",
                                        GerenciadorArquivos.getFuncionarios().get(i).getCr()};
            modelo.addRow(linha);
        }
        
        
        tblFuncionarios.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomePesquisar = new javax.swing.JTextField();
        btncPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnEditarFuncionario = new javax.swing.JButton();
        btnDeletarFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Filtrar por CPF:");

        btncPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3844432-magnifier-search-zoom_110300.png"))); // NOI18N

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Data de nascimento", "Sexo", "Cargo", "CR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblFuncionariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblFuncionariosFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionarios);

        btnEditarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_icon-icons.com_61193.png"))); // NOI18N
        btnEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncionarioActionPerformed(evt);
            }
        });

        btnDeletarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3844424_can_delete_remove_trash_icon.png"))); // NOI18N
        btnDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomePesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncPesquisar)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(206, Short.MAX_VALUE)
                        .addComponent(btnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(btnDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btncPesquisar))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFuncionariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblFuncionariosFocusGained
        
    }//GEN-LAST:event_tblFuncionariosFocusGained

    private void tblFuncionariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblFuncionariosFocusLost
       
    }//GEN-LAST:event_tblFuncionariosFocusLost

    private void btnEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioActionPerformed
        if (tblFuncionarios.getSelectedRowCount() != 0) {
            int index = tblFuncionarios.getSelectedRow();
            new AdicionarFuncionario(arquivo, index).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um funcionário da tabela", "Funcionário não escolhido", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarFuncionarioActionPerformed

    private void btnDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarFuncionarioActionPerformed
        if (tblFuncionarios.getSelectedRowCount() != 0) {
            int index = tblFuncionarios.getSelectedRow();
        
            if (index>=0 && index<GerenciadorArquivos.getAnimais().size()) {
                arquivo.removerObjeto(1, GerenciadorArquivos.getAnimais().get(index));
                carregarTabelaFuncionarios();
                
                
            }
        } else if (tblFuncionarios.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Escolha apenas um animal da tabela", "Mais de um animal escolhido", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Escolha um animal da tabela", "Animal não escolhido", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnDeletarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalisarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarFuncionario;
    private javax.swing.JButton btnEditarFuncionario;
    private javax.swing.JButton btncPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtNomePesquisar;
    // End of variables declaration//GEN-END:variables
}
