/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasDiretor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import zoologico.Biologo;
import zoologico.Funcionario;
import zoologico.GerenciadorArquivos;

// Tela feita para a análise de funcionários existentes, podendo editá-los e excluí-los

/**
 *
 * @author gugas
 */
public class AnalisarFuncionario extends javax.swing.JFrame {
    GerenciadorArquivos arquivo;
    ArrayList<Integer> funcionariosFiltrados = new ArrayList<Integer>();
    boolean filtrado;
    /**
     * Creates new form AnalisarFuncionario
     * @param arquivo
     */
    
    
    public AnalisarFuncionario() {
        initComponents();
        
        jrCpf.setSelected(true);
        txtNomePesquisar.setEnabled(false);
        
        setLocationRelativeTo(null);
        carregarTabelaFuncionarios();
       
    }
    
    public AnalisarFuncionario(GerenciadorArquivos arquivo) {
        this.arquivo = arquivo;
        
        initComponents();
        
        jrCpf.setSelected(true);
        txtNomePesquisar.setEnabled(false);
        
        setLocationRelativeTo(null);
        carregarTabelaFuncionarios(); 
    }
    
    public void carregarTabelaPesFuncionario(String comparar, boolean flag){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"CPF", "Nome", "Data de nascimento", "Sexo", "Cargo", "CR"}, 0);
        
        for(int i=1;i < GerenciadorArquivos.getFuncionarios().size(); i++) {
                if(flag == true){
                    if (GerenciadorArquivos.getFuncionarios().get(i).getCpf().toLowerCase().startsWith(comparar)) {
                        funcionariosFiltrados.add(i);
                        Object linha[] = new Object[]{GerenciadorArquivos.getFuncionarios().get(i).getCpf(),
                                                    GerenciadorArquivos.getFuncionarios().get(i).getNome(),
                                                    GerenciadorArquivos.getFuncionarios().get(i).getDataNascimento(),
                                                    GerenciadorArquivos.getFuncionarios().get(i).getSexo(),
                                                    GerenciadorArquivos.getFuncionarios().get(i) instanceof Biologo ? "Biólogo" : "Veterinário",
                                                    GerenciadorArquivos.getFuncionarios().get(i).getCr()};
                        modelo.addRow(linha);
                    }
                }
                else if(GerenciadorArquivos.getFuncionarios().get(i).getNome().toLowerCase().startsWith(comparar)){
                    funcionariosFiltrados.add(i);
                    Object linha[] = new Object[]{GerenciadorArquivos.getFuncionarios().get(i).getCpf(),
                                            GerenciadorArquivos.getFuncionarios().get(i).getNome(),
                                            GerenciadorArquivos.getFuncionarios().get(i).getDataNascimento(),
                                            GerenciadorArquivos.getFuncionarios().get(i).getSexo(),
                                            GerenciadorArquivos.getFuncionarios().get(i) instanceof Biologo ? "Biólogo" : "Veterinário",
                                            GerenciadorArquivos.getFuncionarios().get(i).getCr()};
                modelo.addRow(linha);
                } 
                    
            }
        tblFuncionarios.setModel(modelo); 
    }
    
    public void carregarTabelaFuncionarios(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"CPF", "Nome", "Data de nascimento", "Sexo", "Cargo", "CR"}, 0);
        
        for(int i=1;i < GerenciadorArquivos.getFuncionarios().size(); i++) {
            
            Object linha[] = new Object[]{GerenciadorArquivos.getFuncionarios().get(i).getCpf(),
                                        GerenciadorArquivos.getFuncionarios().get(i).getNome(),
                                        GerenciadorArquivos.getFuncionarios().get(i).getDataNascimento(),
                                        GerenciadorArquivos.getFuncionarios().get(i).getSexo(),
                                        GerenciadorArquivos.getFuncionarios().get(i) instanceof Biologo ? "Biólogo" : "Veterinário",
                                        GerenciadorArquivos.getFuncionarios().get(i).getCr()};
            modelo.addRow(linha);
        }
        tblFuncionarios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnEditarFuncionario = new javax.swing.JButton();
        btnDeletarFuncionario = new javax.swing.JButton();
        btncPesquisar = new javax.swing.JButton();
        txtNomePesquisar = new javax.swing.JTextField();
        txtCpfPesquisar = new javax.swing.JTextField();
        jrCpf = new javax.swing.JRadioButton();
        jrNome = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Data de nascimento", "Sexo", "Cargo", "CR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblFuncionariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblFuncionariosFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionarios);

        btnEditarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_icon-icons.com_61193.png"))); // NOI18N
        btnEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncionarioActionPerformed(evt);
            }
        });

        btnDeletarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3844424_can_delete_remove_trash_icon.png"))); // NOI18N
        btnDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarFuncionarioActionPerformed(evt);
            }
        });

        btncPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3844432-magnifier-search-zoom_110300.png"))); // NOI18N
        btncPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncPesquisarActionPerformed(evt);
            }
        });

        txtNomePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePesquisarActionPerformed(evt);
            }
        });

        txtCpfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfPesquisarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrCpf);
        jrCpf.setText("Filtrar por CPF:");
        jrCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCpfActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrNome);
        jrNome.setText("Filtrar por Nome:");
        jrNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(233, Short.MAX_VALUE)
                        .addComponent(btnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(btnDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrCpf)
                            .addComponent(jrNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpfPesquisar)
                            .addComponent(txtNomePesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncPesquisar)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncPesquisar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrNome))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFuncionariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblFuncionariosFocusGained
        
    }//GEN-LAST:event_tblFuncionariosFocusGained

    private void tblFuncionariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblFuncionariosFocusLost
       
    }//GEN-LAST:event_tblFuncionariosFocusLost

    private void btnEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioActionPerformed
        if (tblFuncionarios.getSelectedRowCount() == 1) {
            int index = 0;
            System.out.println(filtrado);
            if (filtrado == false) {
                index = tblFuncionarios.getSelectedRow() + 1;
            } else {
                index = funcionariosFiltrados.get(tblFuncionarios.getSelectedRow());
                System.out.println(index);
            }
            new AdicionarFuncionario(arquivo, index).setVisible(true);
        } else if (tblFuncionarios.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Escolha apenas um funcionário da tabela", "Mais de um funcionário escolhido", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Escolha um funcionário da tabela", "Funcionário não escolhido", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarFuncionarioActionPerformed

    private void btnDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarFuncionarioActionPerformed
        if (tblFuncionarios.getSelectedRowCount() == 1) {
            int index = 0;
            System.out.println(filtrado);
            if (filtrado == false) {
                index = tblFuncionarios.getSelectedRow() + 1;
            } else {
                index = funcionariosFiltrados.get(tblFuncionarios.getSelectedRow());
                System.out.println(index);
            }
        
            if (index>=0 && index<GerenciadorArquivos.getFuncionarios().size()) {
                arquivo.removerObjeto(1, GerenciadorArquivos.getFuncionarios().get(index));
                btncPesquisar.doClick();
                
                
            }
        } else if (tblFuncionarios.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Escolha apenas um funcionário da tabela", "Mais de um funcionário escolhido", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Escolha um funcionário da tabela", "Funcionário não escolhido", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnDeletarFuncionarioActionPerformed

    private void btncPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncPesquisarActionPerformed
        String comparar;
        boolean flag;
        if (txtCpfPesquisar.getText().equals("") && txtCpfPesquisar.getText().equals("")) filtrado = false;
        else filtrado = true;
        funcionariosFiltrados.clear();
        if(jrCpf.isSelected()){
            if (txtCpfPesquisar.getText().equals("")) {
                carregarTabelaFuncionarios();
            } else {
                comparar = txtCpfPesquisar.getText().toLowerCase();
                flag = true;
                carregarTabelaPesFuncionario(comparar, flag);
            }
            
        }
        else {
            if (txtNomePesquisar.getText().equals("")) {
                carregarTabelaFuncionarios();
            } else {
                comparar = txtNomePesquisar.getText().toLowerCase();
                flag = false;
                carregarTabelaPesFuncionario(comparar, flag);
            }
        }
    }//GEN-LAST:event_btncPesquisarActionPerformed

    private void jrNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNomeActionPerformed
        txtNomePesquisar.setEnabled(true);
        txtCpfPesquisar.setEnabled(false);
    }//GEN-LAST:event_jrNomeActionPerformed

    private void txtCpfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfPesquisarActionPerformed
        
    }//GEN-LAST:event_txtCpfPesquisarActionPerformed

    private void jrCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCpfActionPerformed
        txtNomePesquisar.setEnabled(false);
        txtCpfPesquisar.setEnabled(true);
    }//GEN-LAST:event_jrCpfActionPerformed

    private void txtNomePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalisarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarFuncionario;
    private javax.swing.JButton btnEditarFuncionario;
    private javax.swing.JButton btncPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrCpf;
    private javax.swing.JRadioButton jrNome;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtCpfPesquisar;
    private javax.swing.JTextField txtNomePesquisar;
    // End of variables declaration//GEN-END:variables
}
