/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasDiretor;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import telas.EditarPerfil;
import telas.TelasBiologo.AnalisarRecinto;
import telas.TelasVeterinario.AnalisarAnimal;
import zoologico.Diretor;
import zoologico.GerenciadorArquivos;

/**
 *
 * @author Vinicius
 */
public class DiretorTela extends javax.swing.JFrame {

    GerenciadorArquivos arquivo;
    /**
     * Creates new form Diretor
     * @param arquivo
     */
    public DiretorTela(GerenciadorArquivos arquivo, Diretor diretorEscolhido) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.arquivo = arquivo;
        
        addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    try {
                        arquivo.exportarArquivos();
                    } catch (Exception ex) {}
                }
            });
    }
    
    public DiretorTela(GerenciadorArquivos arquivo) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.arquivo = arquivo;
        
        addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    try {
                        arquivo.exportarArquivos();
                    } catch (Exception ex) {}
                }
            });
    }
    
    public DiretorTela() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    try {
                        arquivo.exportarArquivos();
                    } catch (Exception ex) {}
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();
        btnRecinto = new javax.swing.JButton();
        btnAnimais = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setText("Bem-vindo");

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel2.setText("Cargo: Diretor");

        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lapis.png"))); // NOI18N
        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarPerfil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        btnRecinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pinheiro-64.png"))); // NOI18N
        btnRecinto.setText("RECINTOS");
        btnRecinto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecinto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRecinto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecintoActionPerformed(evt);
            }
        });

        btnAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/urso.png"))); // NOI18N
        btnAnimais.setText("ANIMAIS");
        btnAnimais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnimais.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAnimais.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimaisActionPerformed(evt);
            }
        });

        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-funcionário-homem-64.png"))); // NOI18N
        btnFuncionario.setText("FUNCIONÁRIOS");
        btnFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFuncionario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setText("(nome)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarPerfil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAnimais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(btnEditarPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecinto)
                    .addComponent(btnAnimais)
                    .addComponent(btnFuncionario))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        new Funcionarios(arquivo).setVisible(true);
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btnRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecintoActionPerformed
        new AnalisarRecinto(arquivo).setVisible(true);
    }//GEN-LAST:event_btnRecintoActionPerformed

    private void btnAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimaisActionPerformed
        new AnalisarAnimal(arquivo).setVisible(true);
    }//GEN-LAST:event_btnAnimaisActionPerformed

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        new EditarPerfil().setVisible(true);
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiretorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiretorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiretorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiretorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiretorTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimais;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnRecinto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
