/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas.TelasDiretor;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import zoologico.GerenciadorArquivos;
import zoologico.Recinto;

// Tela feita para escolher um recinto para adicionar como responsabilidade à um biólogo na sua criação ou edição
// Além disso, também é utilizada para escolher o recinto no qual o animal será alocado


public class EscolheRecinto extends javax.swing.JFrame {
    ArrayList<String> idRecintos;
    JButton btnAtualizarResp;
    ArrayList<Recinto> recintoEscolhido;
    boolean ehAnimal;
    JLabel labelRecinto;
    /**
     * Creates new form EscolheAnimal
     */
    public EscolheRecinto() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        carregarTabelaRecintos();
    }
    
    public EscolheRecinto(ArrayList<Recinto> recintoEscolhido, JLabel labelRecinto) {
        initComponents();
        
        this.recintoEscolhido = recintoEscolhido;
        this.ehAnimal = true;
        this.labelRecinto = labelRecinto;
        
        setLocationRelativeTo(null);
        
        carregarTabelaRecintos();
    }
    
    public EscolheRecinto(ArrayList<String> idRecintos, JButton btnAtualizarResp) {
        initComponents();

        this.idRecintos = idRecintos;
        this.btnAtualizarResp = btnAtualizarResp;
        
        setLocationRelativeTo(null);
        
        carregarTabelaRecintos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmarRecinto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecintos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnConfirmarRecinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/check.png"))); // NOI18N
        btnConfirmarRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRecintoActionPerformed(evt);
            }
        });

        tblRecintos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
            },
            new String [] {
                "Tipo de recinto", "Família", "Vegetação"
            }
        ));
        jScrollPane2.setViewportView(tblRecintos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarRecinto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmarRecinto)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarTabelaRecintos(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Tipo de recinto", "Família", "Vegetação"}, 0);
        
        for(int i=0;i < GerenciadorArquivos.getRecintos().size(); i++) {
            Object linha[] = new Object[]{GerenciadorArquivos.getRecintos().get(i).toString(),
                GerenciadorArquivos.getRecintos().get(i).getFamilia(),
                GerenciadorArquivos.getRecintos().get(i).getTipoVegetação()};
            modelo.addRow(linha);
        }
        
        tblRecintos.setModel(modelo);
    }
    
    private void btnConfirmarRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRecintoActionPerformed
        if (idRecintos == null) {
            if (tblRecintos.getSelectedRowCount() == 1) {
                Recinto rec = GerenciadorArquivos.getRecintos().get(tblRecintos.getSelectedRow());
                recintoEscolhido.add(rec);
                labelRecinto.setText(rec.getFamilia());
                dispose();
            } else if (tblRecintos.getSelectedRowCount() > 1) {
                JOptionPane.showMessageDialog(null, "Escolha apenas um recinto da tabela", "Mais de um recinto escolhido", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha um recinto da tabela", "Recinto não escolhido", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            System.out.println("tesetetsetet");
            if (tblRecintos.getSelectedRowCount() != 0) {
                for (int i=0; i < tblRecintos.getSelectedRows().length; i++) {
                    idRecintos.add(GerenciadorArquivos.getRecintos().get(tblRecintos.getSelectedRows()[i]).getRecintoId());
                }
                System.out.println(idRecintos);
                btnAtualizarResp.doClick();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Escolha um recinto da tabela", "Recinto não escolhido", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnConfirmarRecintoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolheRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolheRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolheRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolheRecinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolheRecinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarRecinto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRecintos;
    // End of variables declaration//GEN-END:variables
}
